### ISSUE TITLE
Will this work across networks if I uncomment the google stun server?

### ISSUE THREAD

**Issue by didlie** [owebio/serverless-webrtc-chat#1]
Will this work across networks if I uncomment the google stun server?

I haven't tried it yet

**Comment by owebio** [comment]
Yes it works when you put stun servers. 
``` javascript
var pc = new RTCPeerConnection({"iceServers": [{"url": "stun:stun.l.google.com:19302"}]});
```
Try this one, please.

**Comment by didlie** [comment]
https://github.com/didlie/didlie.com-website-webrtc-chat
Here is a php/javascript solution that works. It will be published to didlie.com as v2 soon. If you do php, you only need to change the file references in chat.php to match your file structure, and include chat.js.php in your website page with includes for the other php files, and its off and running. I plan to generalize this github version, for easy contribution from other github developers.
